# Generated by Django 5.2.14 on 2026-05-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_workinghours_vacancy_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiCorruptionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='anti_corruption_docs/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Антикоррупционный документ',
                'verbose_name_plural': 'Антикоррупционные документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorruptionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО нарушителя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='corruption_reports/', verbose_name='Вложение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Репорт о коррупции',
                'verbose_name_plural': 'Репорты о коррупции',
                'ordering': ['-created_at'],
            },
        ),
    ]
