# Generated by Django 5.2.14 on 2026-06-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_anticorruptiondocument_corruptionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='consent_false_info',
            field=models.BooleanField(default=False, help_text='Известно, что ложные сведения и несоответствие требованиям влекут отказ', verbose_name='Согласие с последствиями ложных сведений'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='consent_personal_data',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных (152-ФЗ)'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='consent_resume_forwarding',
            field=models.BooleanField(default=False, verbose_name='Согласие на направление анкеты в поселения и организации района'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='consent_verification',
            field=models.BooleanField(default=False, verbose_name='Согласие на проверочные мероприятия'),
        ),
    ]
