# Generated by Django 5.2.14 on 2026-06-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_jobapplication_consent_false_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='show_on_main_page',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной странице тендеров'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='consent_false_info',
            field=models.BooleanField(default=False, verbose_name='Согласие с последствиями ложных сведений'),
        ),
    ]
