# Generated by Django 5.2.14 on 2026-06-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.AddField(
            model_name='corruptionreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='corruption_images/', verbose_name='Изображение'),
        ),
    ]
