# Generated by Django 5.2.14 on 2026-06-28 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_feedback_email_remove_feedback_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchesglobal',
            options={'ordering': ['order'], 'verbose_name': 'Отдел Администрации', 'verbose_name_plural': 'Все отделы Администрации'},
        ),
    ]
