# Generated by Django 5.2.14 on 2026-06-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_branchesglobal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchesglobal',
            options={'ordering': ['name'], 'verbose_name': 'Отдел Администрации', 'verbose_name_plural': 'Все отделы Администрации'},
        ),
        migrations.RemoveField(
            model_name='branchesglobal',
            name='order',
        ),
    ]
