# Generated by Django 5.2.14 on 2026-06-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_branchesglobal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='show_on_reserve',
            field=models.BooleanField(default=False, verbose_name='Показывать в кадровом резерве'),
        ),
    ]
