# Generated by Django 5.2.14 on 2026-06-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_staffmember_show_on_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('branch', models.CharField(blank=True, max_length=255, verbose_name='Орган/отдел')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('job_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jobtype', verbose_name='Тип должности')),
                ('required_experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.requiredexperience', verbose_name='Требуемый опыт')),
                ('work_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.workschedule', verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'Подписка на вакансии',
                'verbose_name_plural': 'Подписки на вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
