# Generated by Django 5.2.14 on 2026-06-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_vacancy_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('competition_type', models.CharField(choices=[('vacancy', 'На замещение вакантной должности'), ('reserve', 'На формирование кадрового резерва')], default='vacancy', max_length=20, verbose_name='Тип конкурса')),
                ('content', models.TextField(blank=True, verbose_name='Содержание (веб-контент)')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала приёма документов')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания приёма документов')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('acceptance_info', models.TextField(blank=True, verbose_name='Место и время приёма документов')),
                ('contact_phones', models.CharField(blank=True, max_length=500, verbose_name='Телефоны ответственных лиц')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий конкурс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурсы',
                'ordering': ['-date_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('decree_conduct', models.FileField(upload_to='competitions/conduct/', verbose_name='Постановление о проведении конкурса')),
                ('decree_results', models.FileField(upload_to='competitions/results/', verbose_name='Постановление о результатах конкурса')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Результат конкурса',
                'verbose_name_plural': 'Результаты конкурсов',
                'ordering': ['-completed_at', '-created_at'],
            },
        ),
    ]
