# Generated by Django 5.2.14 on 2026-06-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_competition_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffReserveInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(blank=True, default='Формирование кадрового резерва направлено на обеспечение администрации Сургутского района квалифицированными кадрами для замещения вакантных должностей.', verbose_name='Цель формирования кадрового резерва')),
                ('positions', models.TextField(blank=True, help_text='Каждая должность с новой строки', verbose_name='Должности, на которые формируется резерв')),
                ('additional_content', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница «Кадровый резерв»',
                'verbose_name_plural': 'Страница «Кадровый резерв»',
            },
        ),
    ]
