# Generated by Django 5.2.14 on 2026-06-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_staff_reserve_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('educational_institution', models.CharField(max_length=255, verbose_name='Учебное заведение')),
                ('course', models.CharField(max_length=50, verbose_name='Курс')),
                ('specialty', models.CharField(max_length=255, verbose_name='Специальность')),
                ('practice_period', models.CharField(max_length=255, verbose_name='Желаемый период практики')),
                ('preferred_department', models.CharField(blank=True, max_length=255, verbose_name='Желаемое подразделение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('application_letter', models.FileField(blank=True, null=True, upload_to='practice_applications/', verbose_name='Сопроводительное письмо')),
                ('consent_personal_data', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных (152-ФЗ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
            ],
            options={
                'verbose_name': 'Заявка на практику',
                'verbose_name_plural': 'Заявки на практику',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, default='Раздел предназначен для популяризации муниципальной службы и ранней профориентации.', verbose_name='Вводный текст')),
                ('practice_institutions', models.TextField(blank=True, help_text='Каждое учебное заведение с новой строки', verbose_name='Учебные заведения (соглашения)')),
                ('practice_steps', models.TextField(blank=True, default='1. Ознакомьтесь с перечнем учебных заведений, с которыми заключены соглашения.\n2. Согласуйте прохождение практики с учебным заведением.\n3. Заполните и отправьте заявку на практику через форму на этой странице.\n4. Дождитесь ответа специалиста управления муниципальной службы, кадров и наград.', verbose_name='Этапы: как попасть на практику в АСР')),
                ('internship_content', models.TextField(blank=True, default='Информация о стажировках будет размещена дополнительно.', verbose_name='Стажировка')),
                ('school_content', models.TextField(blank=True, default='Информация для школьников будет размещена дополнительно.', verbose_name='Школьникам')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница «Муниципальная служба для молодёжи»',
                'verbose_name_plural': 'Страница «Муниципальная служба для молодёжи»',
            },
        ),
    ]
