# Generated by Django 5.2.14 on 2026-06-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_youth_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('event_type', models.CharField(choices=[('training', 'Обучающее мероприятие'), ('leadership', 'Встреча с руководством'), ('masterclass', 'Мастер-класс'), ('best_practice', 'Лучшая практика')], default='training', max_length=20, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_date', models.DateTimeField(verbose_name='Дата и время')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место проведения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Обучающее мероприятие',
                'verbose_name_plural': 'Обучающие мероприятия',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Подразделение')),
                ('message', models.TextField(verbose_name='Предложение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Предложение по обучению',
                'verbose_name_plural': 'Предложения по обучению',
                'ordering': ['-created_at'],
            },
        ),
    ]
