# Generated by Django 5.2.14 on 2026-06-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_training_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiCorruptionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, default='Федеральный закон от 25.12.2008 № 273-ФЗ «О противодействии коррупции» устанавливает правовые и организационные основы предупреждения и борьбы с коррупцией.', verbose_name='Вводный текст')),
                ('work_schedule', models.TextField(blank=True, default='Понедельник – четверг: 8:30 – 17:30\nПятница: 8:30 – 16:15\nПерерыв: 13:00 – 13:45', verbose_name='График работы УМСКН')),
                ('address', models.TextField(blank=True, default='628408, Ханты-Мансийский автономный округ — Югра, г. Сургут, ул. 30 лет Победы, д. 45/2', verbose_name='Адрес')),
                ('officials', models.TextField(blank=True, help_text='Каждый сотрудник с новой строки: ФИО, должность, телефон', verbose_name='Ответственные должностные лица')),
                ('esia_feedback_url', models.URLField(blank=True, default='https://pos.gosuslugi.ru/landing/', verbose_name='Ссылка на Платформу обратной связи (ЕСИА)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница «Противодействие коррупции»',
                'verbose_name_plural': 'Страница «Противодействие коррупции»',
            },
        ),
    ]
