# Generated by Django 5.2.14 on 2026-06-30 07:31

from datetime import date

from django.db import migrations, models


def seed_news(apps, schema_editor):
    NewsPost = apps.get_model('api', 'NewsPost')
    if NewsPost.objects.exists():
        return
    NewsPost.objects.bulk_create([
        NewsPost(
            title='Спортивный конкурс между отделами',
            description='Такого-то числа у нас проходит конкурс...',
            published_at=date(2024, 11, 25),
            order=1,
        ),
        NewsPost(
            title='Время близится к первому декабря, заплатил налог?',
            description='Приходите в налоговую...',
            published_at=date(2024, 11, 4),
            order=2,
        ),
        NewsPost(
            title='Поздравляем с Днем госслужащего!',
            description='Глава нашего Сургутского района спешит вас поздравить...',
            published_at=date(2024, 8, 22),
            order=3,
        ),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_anti_corruption_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('content', models.TextField(blank=True, verbose_name='Полный текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('published_at', models.DateField(verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('show_on_main', models.BooleanField(default=True, verbose_name='Показывать на главной')),
                ('order', models.PositiveIntegerField(default=0, help_text='Меньшее число — выше в списке', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['order', '-published_at'],
            },
        ),
        migrations.RunPython(seed_news, migrations.RunPython.noop),
    ]
