# Generated by Django 5.2.14 on 2026-07-01 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_simplify_vacancy_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('intro', models.TextField(blank=True, default='Отраслевой (функциональный) орган администрации Сургутского района обеспечивает реализацию полномочий в своей сфере деятельности и взаимодействует с жителями района.', verbose_name='Краткое описание')),
                ('about_paragraphs', models.TextField(blank=True, help_text='Каждый абзац с новой строки', verbose_name='О деятельности')),
                ('units', models.TextField(blank=True, help_text='Каждое подразделение с новой строки', verbose_name='Структурные подразделения')),
                ('tasks', models.TextField(blank=True, help_text='Каждая задача с новой строки', verbose_name='Задачи')),
                ('head_name', models.CharField(blank=True, max_length=255, verbose_name='Руководитель: ФИО')),
                ('head_role', models.CharField(blank=True, max_length=255, verbose_name='Руководитель: должность')),
                ('head_phone', models.CharField(blank=True, max_length=255, verbose_name='Руководитель: телефон')),
                ('head_email', models.EmailField(blank=True, max_length=254, verbose_name='Руководитель: email')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('image', models.ImageField(blank=True, null=True, upload_to='departments/', verbose_name='Фото')),
                ('vacancy_branch', models.CharField(blank=True, help_text='Должно совпадать с полем «Отдел» в вакансиях', max_length=500, verbose_name='Название для вакансий')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Орган администрации',
                'verbose_name_plural': 'Органы администрации',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255, verbose_name='Должность')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('image', models.CharField(blank=True, help_text='Например: /images/people/markova.png', max_length=500, verbose_name='Фото (URL или путь)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Заместитель главы',
                'verbose_name_plural': 'Заместители главы',
                'ordering': ['order', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='DeputyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department', verbose_name='Орган')),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deputy_departments', to='api.deputy', verbose_name='Заместитель')),
            ],
            options={
                'verbose_name': 'Орган заместителя',
                'verbose_name_plural': 'Органы заместителей',
                'ordering': ['order'],
                'unique_together': {('deputy', 'department')},
            },
        ),
        migrations.AddField(
            model_name='deputy',
            name='departments',
            field=models.ManyToManyField(related_name='deputies', through='api.DeputyDepartment', to='api.department', verbose_name='Органы'),
        ),
    ]
