# Generated by Django 5.2.14 on 2026-07-02 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_staffmember_proxies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterField(
            model_name='practiceapplication',
            name='preferred_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Желаемый орган'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch', verbose_name='Отдел'),
        ),
    ]
