# Generated by Django 5.2.14 on 2026-07-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_workpartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthinfo',
            name='practice_steps',
            field=models.TextField(blank=True, default='1. Определитесь, в каком отраслевом функциональном органе вы хотите проходить практику. Со структурой администрации можно ознакомиться в разделе [«О нас»](/about#admin-structure).\n2. Согласуйте прохождение практики с учебным заведением.\n3. Заполните и отправьте заявку на практику через форму на этой странице.\n4. Дождитесь ответа специалиста управления муниципальной службы, кадров и наград.', verbose_name='Этапы: как попасть на практику в АСР'),
        ),
    ]
